"""Add User model

Revision ID: dfa921c5170e
Revises: c4cd02d3c886
Create Date: 2025-09-20 20:22:04.594528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfa921c5170e'
down_revision = 'c4cd02d3c886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.drop_table('patient_worker_connections')
    op.drop_table('vital_records')
    op.drop_table('reminders')
    op.drop_table('users')
    op.drop_table('health_content')
    op.drop_table('health_workers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_workers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('health_workers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('worker_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('certification_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('specializations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('coverage_areas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('languages', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='health_workers_pkey'),
    sa.UniqueConstraint('certification_id', name='health_workers_certification_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('email', name='health_workers_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('phone', name='health_workers_phone_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('health_content',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('health_content_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('village_city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('conditions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preferred_language', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('phone', name='users_phone_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('reminders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reminder_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('medication_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('dosage', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('scheduled_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('frequency', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('days_of_week', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notification_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_triggered', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_trigger', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('reminders_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reminders_pkey'))
    )
    op.create_table('vital_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blood_sugar', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('blood_pressure_systolic', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blood_pressure_diastolic', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('heart_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('measurement_time', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('before_after_meal', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('vital_records_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vital_records_pkey'))
    )
    op.create_table('patient_worker_connections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('health_worker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('connection_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('connected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_contact', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['health_worker_id'], ['health_workers.id'], name=op.f('patient_worker_connections_health_worker_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('patient_worker_connections_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('patient_worker_connections_pkey'))
    )
    op.drop_table('user')
    # ### end Alembic commands ###
