"""add temperature and oxygen_level to vital_records

Revision ID: e3d41416b2db
Revises: 9438b689e581
Create Date: 2025-09-29 01:16:17.161035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d41416b2db'
down_revision = '9438b689e581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vital_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('oxygen_level', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vital_records', schema=None) as batch_op:
        batch_op.drop_column('oxygen_level')
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###
